version: '3.5'

services:
  db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
  
  catalog:
    container_name: catalog-service
    image: catalog-service
    env_file: ./.env
    build:
      context: ./backend/services/catalog/
    depends_on:
      - db
      - mq
      - identity
    ports:
      - "5121:5121"

  identity:
    container_name: identity-service
    image: quay.io/keycloak/keycloak:legacy
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=mysql-db
      - DB_DATABASE=identitydb
      - DB_USER=root
      - DB_SCHEMA=public
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8090:8080"
      - "8543:8443"
    volumes:
      - "/home/ec2-user/eshop/backend/services/identity/https/:/etc/x509/https"

  basket:
    container_name: basket-service
    image: basket-service
    env_file: ./.env
    build:
      context: ./backend/services/basket/
    depends_on:
      - basket-db
      - mq
      - identity
    ports:
      - "5122:5122"

  mq:
    container_name: rabbit-mq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  order:
    container_name: order-service
    image: order-service
    env_file: ./.env
    build:
      context: ./backend/services/order/
    depends_on:
      - db
      - mq
      - identity
    ports:
      - "5123:5123"

  payment:
    container_name: payment-service
    image: payment-service
    env_file: ./.env
    build:
      context: ./backend/services/payment/
    depends_on:
      - db
      - mq
      - identity
    ports:
      - "5124:5124"

  notification:
    container_name: notification-service
    image: notification-service
    env_file: ./.env
    build:
      context: ./backend/services/notification/
    depends_on:
      - db
      - mq
      - identity
    ports:
      - "5125:5125"

  basket-db:
    container_name: basket-db
    image: redis:alpine
    ports:
      - "6379:6379"

  content:
    container_name: content-service
    image: content-service
    env_file: ./.env
    build:
      context: ./backend/services/content/
    depends_on:
      - mq
      - identity
    ports:
      - "5126:5126"
    volumes:
      - content:/content

  gateway:
    container_name: api-gateway
    image: api-gateway
    env_file: ./.env
    build:
      context: ./backend/gateways/gateway/
    depends_on:
      - identity
    ports:
      - "8080:8080"

volumes:
  content:
