version: '3.5'

services:
  db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
  
  catalog:
    container_name: catalog-service
    image: catalog-service
    build:
      context: ./services/catalog/
    depends_on:
      - db
      - identity
    ports:
      - "5121:5121"

  identity:
    container_name: identity-service
    image: quay.io/keycloak/keycloak:17.0.0
    command: ['start-dev', '--http-port=8180']
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8180:8180"

  basket:
    container_name: basket-service
    image: basket-service
    build:
      context: ./services/basket/
    depends_on:
      - db
      - identity
    ports:
      - "5122:5122"
