version: '3.5'

services:
  db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
  
  catalog:
    container_name: catalog-service
    image: catalog-service
    build:
      context: ./services/catalog/
    depends_on:
      - db
      - mq
      - identity
    ports:
      - "5121:5121"

  identity:
    container_name: identity-service
    image: quay.io/keycloak/keycloak:17.0.0
    command: ['start-dev', '--http-port=8180']
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql-db:3306/identitydb
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=password
    ports:
      - "8180:8180"

  basket:
    container_name: basket-service
    image: basket-service
    build:
      context: ./services/basket/
    depends_on:
      - db
      - mq
      - identity
    ports:
      - "5122:5122"

  mq:
    container_name: rabbit-mq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  order:
    container_name: order-service
    image: order-service
    build:
      context: ./services/order/
    depends_on:
      - db
      - mq
      - identity
    ports:
      - "5123:5123"

  payment:
    container_name: payment-service
    image: payment-service
    build:
      context: ./services/payment/
    depends_on:
      - db
      - mq
      - identity
    ports:
      - "5124:5124"
