name: Label Triggered Workflow
run-name: ${{ github.actor }} is testing out the Label Triggered Workflow  🚀
on: 
  pull_request:
    types:
      [ labeled ]
jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
          LABELS: ${{ toJSON(github.event.pull_request.labels) }}
        run: |
          for x in ${{ github.event.pull_request.labels }}; do
            echo "$x"
          done
  conditional_job:
    if: ${{ github.event.label.name == 'in-testing' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "PR now has label in-testing"
